name: Release
on: [push]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Release
        run: bun semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
